services:
  backend:
    build: .
    container_name: car-detect-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - USE_GPU=False
      - DEVICE=cpu
    restart: always
