
services:
  backend:
    build: .
    container_name: car-detect-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
      - USE_GPU=False
      - DEVICE=cpu
    restart: always
